### ISSUE TITLE
Validation should account for `#ost/api/ex/${TAG_NAME}` links

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-epub#103]
I just noticed that baking HS Physics produces validation errors of the form:

```
cnxepub ERROR Bad href: #ost/api/ex/k12phys-ch22-ex013
```

but these are expected since they will be loaded and replaced either in webview or as part of publishing.

/cc @reedstrm

**Comment by reedstrm** [comment]
@philschatz - nope, once the correct baking path is in place Connexions/cnx-publishing#144 all of those links should be converted in place.
