### ISSUE TITLE
data namespace remains on elements after publish

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-epub#47]
Most of the namespaces added by the editor are being removed by cnx-epub. However, the data name space in still in the published html when there is not a data- attribute on the element.

3 examples
http://dev.cnx.org/contents/f5384526-c6af-4d66-a2db-45c8177ea2f7/Test-3-19
http://dev.cnx.org/contents/03d06701-9b79-4561-bb72-a3ace4bed2a4/CNX-EPUB-Fix-Test
http://dev.cnx.org/contents/ff20cc94-230b-40e9-b19c-d78cfdfcc86b/CNX-EPUB-Test-2

**Comment by pumazi** [comment]
Looks like the old dev.w3.org namespace is still in the content.

**Comment by pumazi** [comment]
I think Ross caught the final bits of this in #46.
