### ISSUE TITLE
Change in-book links to relative links?

### ISSUE THREAD

**Issue by karenc** [Connexions/cnx-epub#87]
A question was raised in #86 by @philschatz:

Could/should inter-module links be converted so their URL is `./{UUID}` instead of `/contents/{UUID}`? It seems like that would work for online, epub, hosting-yourself-by-unzipping-the-EPUB, and it wouldn't hardcode `/contents/` into the paths if we switch to something like `/c/`

**Comment by brittweinstein** [comment]
Closing due to issue age.
